#!/bin/bash

KEYS="-vp"

print_help()
{
  echo -e "Usage: $(basename $0) [options]\noptions:"
  echo -e "\t-g - group name, eg: \"net-libs\", \"net-*\""
  echo -e "\t-u - use flags,  eg: \"X icu\""
  echo -e "\t-i - install, default behavior is pretend"
}

if [ "$#" -lt 1 ]; then
  print_help
  exit 1
fi

while getopts "g:u:ih" opt; do
  case $opt in
    ( g )
      REGEXP="$OPTARG"
      ;;
    ( i )
      KEYS=""
      ;;
    ( u )
      FLAGS="$OPTARG"
      ;;
    ( h )
      print_help
      exit 0
      ;;
    ( * )
      print_help
      exit 1
  esac
done

USE="$FLAGS" emerge $KEYS $(eix -Icu | awk "/${REGEXP}/ {printf \$2\" \"}")
